### ISSUE TITLE
Installing on Unix

### ISSUE THREAD

**Issue by JamesOwers** [tmbdev/ocropy#14]
Hello,

Trying to install on mac OS X Yosemite (10.10.1), using anaconda. Have installed packages in ./PACKAGES manually (curl python-scipy python-matplotlib python-tables firefox imagemagick python-opencv python-bs4) mostly using brew. Following commands threw no warnings:
    $ wget -nd http://www.tmbdev.net/en-default.pyrnn.gz
    $ mv en-default.pyrnn.gz models/
    $ sudo python setup.py install  

Test throws following error:
kungfujams-mbp:ocropy-master kungfujam$ ./run-test
clang: warning: -O4 is equivalent to -O3
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/Users/kungfujam/anaconda/bin/ocropus-nlbin", line 9, in <module>
    import ocrolib
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/ocrolib/**init**.py", line 12, in <module>
    from common import *
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/ocrolib/common.py", line 18, in <module>
    import lstm
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/ocrolib/lstm.py", line 32, in <module>
    import nutils
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/ocrolib/nutils.py", line 25, in <module>
    lstm_native = compile_and_load(lstm_utils)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/ocrolib/native.py", line 67, in compile_and_load
    path = compile_and_find(c_string,**keys)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/ocrolib/native.py", line 63, in compile_and_find
    raise CompileError()
ocrolib.native.CompileError

This may be a gcc/clang issue as seen here: http://stackoverflow.com/questions/20321988/error-enabling-openmp-ld-library-not-found-for-lgomp-and-clang-errors

Any advice gratefully received.

James

**Comment by bbiglari** [comment]
Can you please give me clear guide? I am trying to do so, but I don't understand what does this mean

How should I disable it or get around with this? I am trying to install ocropy on my mac to test some OCR with this.

Thanks

**Comment by jithintomz** [comment]
@bbiglari You can search for native.py file and remove openmp argument from compile_and_find
