### ISSUE TITLE
RecognitionError: input too large for LSTM model

### ISSUE THREAD

**Issue by sdrobac** [tmbdev/ocropy#158]
I am getting the following error:

Traceback (most recent call last):
  File "./ocropus-rtrain", line 286, in <module>
    pcs = network.trainSequence(line,cs,update=do_update,key=fname)
  File "/home/drobac/ocr/ocropy/ocrolib/lstm.py", line 890, in trainSequence
    self.outputs = array(self.lstm.forward(xs))
  File "/home/drobac/ocr/ocropy/ocrolib/lstm.py", line 605, in forward
    xs = net.forward(xs)
  File "/home/drobac/ocr/ocropy/ocrolib/lstm.py", line 661, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/home/drobac/ocr/ocropy/ocrolib/lstm.py", line 551, in forward
    if n>N: raise ocrolib.RecognitionError("input too large for LSTM model")
ocrolib.common.RecognitionError: input too large for LSTM model

I got this error on both a unix machine and a computer cluster, after different number of iterations. I am trying to train a model on 25k and 50k line images which have been binarized and accompanied with corresponding gt.txt files. I am not sure what extra information would be necessary to help debug this, if you need to know something more, please ask.

Does anyone know what might be causing this error and how could I fix it?

**Comment by jbaiter** [comment]
Are your line images wider than 5000 pixels? That's the default maximum length for the input sequences (https://github.com/tmbdev/ocropy/blob/dd02fccf28b7b5fe7db6386044ca79fbcb194b01/ocrolib/lstm.py#L480).

**Comment by jbaiter** [comment]
Can you run with `python -mpdb ocropus-rtrain ...` to get a debugger prompt and then inspect the `n` and `N` variables with `pp n`? Also, it would be good to walk up the stack (with `up`) until you get to the top, where you could inspect the shape of line with `pp line.shape`.

**Comment by sdrobac** [comment]
The widest one is 4639 pixels. Do you think it could be causing this problem? Could I just change `maxlen` to larger value?

I tried running `python -mpdb ocropus-rtrain ...` as you suggested and actually I got different error this time:

/home/drobac/ocr/ocropy/ocropus_venv/local/lib/python2.7/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 387, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "ocropus-rtrain", line 3, in <module>
    import random as pyrandom
  File "ocrolib/lineest.py", line 43, in measure
    self.mad = mean(deltas[line!=0])
  File "/home/drobac/ocr/ocropy/ocropus_venv/local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2885, in mean
    out=out, keepdims=keepdims)
  File "/home/drobac/ocr/ocropy/ocropus_venv/local/lib/python2.7/site-packages/numpy/core/_methods.py", line 70, in _mean
    ret = ret.dtype.type(ret / rcount)
FloatingPointError: invalid value encountered in double_scalars


Any idea what to try with this one?

**Comment by sdrobac** [comment]
Hi,
I rerun the program in debuging mode until got again the same error as in the first post. I checked the values of the variables:
`(Pdb) pp n`
`17744`
`(Pdb) pp N`
`5000`
and
`(Pdb) pp line.shape`
`(17744, 48)`

Do you have any idea why n would be so big or what to do to fix it?

**Comment by Azrael1** [comment]
Anyone know what the issue is, I also got the same error -> pp n/N leads to no output.

**Comment by e1000** [comment]
if I remember correctly, somewhere the _height_ is normalized to *48* pixel, so for example 
if 
```python
height = 24
length = 4000
```,
 it will scale somewhere up to get
```python
height = 48
length = 8000
```

And btw , the line length limit < 5000 is arbitrary (*ocropy* tries to do some memory management by pre-allocating big Numpy-arrays), it could be avoided with some refactoring ...
