### ISSUE TITLE
Cannot run headless - no display name and no $DISPLAY environment variable

### ISSUE THREAD

**Issue by wollmers** [tmbdev/ocropy#161]
## Expected Behavior

Should work as pure shell script without graphic display, e. g.

- ssh
- cron

Should only display if option

    --display

or

    --debug

is set.

## Current Behavior
```
$ ocropus-nlbin tests/ersch.png -o book
# tests/ersch.png
=== tests/ersch.png 1
flattening
/usr/lib/python2.7/dist-packages/scipy/ndimage/interpolation.py:532: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
estimating skew angle
estimating thresholds
rescaling
tests/ersch.png lo-hi (0.00 1.00) angle  0.0 
writing
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-nlbin", line 207, in <module>
    process1((f,i+1))
  File "/usr/local/bin/ocropus-nlbin", line 187, in process1
    gray()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 3670, in gray
    im = gci()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 240, in gci
    return gcf()._gci()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 462, in gcf
    return figure()
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 435, in figure
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1813, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

## Your Environment

* Python version: 
```
Python 2.7.9
```

* Git revision of ocropy: 
```
commit 8e0d3c5ae2d2f1cf0eb082c7a6ca407375437543
Merge: 14e5f44 8819e68
Author: Tom <tmbdev@users.noreply.github.com>
Date:   Tue Nov 4 17:29:16 2014 -0800

    Merge pull request #3 from RLuckom/master
    
    Fixed paths to files in generated html.
```

* Operating System and version:
```
$ cat /etc/debian_version 
8.6
$ uname -a
Linux amd1 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
```

**Comment by zuphilip** [comment]
Thank you for all the information. That makes it easier to help and here it seems useful to see your ocropus version info, which looks outdated.

Please update your OCRopus version with `git pull` (there should be 135 newer commits for you). It looks like this line you are referring to was delete a some time ago: https://github.com/tmbdev/ocropy/compare/8e0d3c5ae2d2f1cf0eb082c7a6ca407375437543...master#diff-9eb7b1611591076b2c66f7d9f42b4997L187

**Comment by wollmers** [comment]
@zuphilip Thanks. Works now after pull.
