### ISSUE TITLE
Invalid charset while training with Telugu language?

### ISSUE THREAD

**Issue by ChillarAnand** [tmbdev/ocropy#162]
I am trying to train ocropy model for telugu language. 10 samples of training data is [available here](https://www.dropbox.com/s/toj8wov9n3ccrgj/train_te.zip) 

When training starts it is doesn't include telugu language,  it just shows 157 chars
```
# inputs 10000
# tests None
# CenterNormalizer
# using default codec
# charset size 157 [ ~!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}¡¢£§©«®°¶»¿ÀÂÄÆÇÈÉÊËÎÏÔÖÙÛÜßàâäæçèéêëîïôö÷ùûüÿŒœŸ†‡•‣‹›€∙▪▫◦]
# last_trial 0
0 304.60 (681, 48) ../samples/0002.png
   TRU: u'\u0c2f\u0c41\u0c35\u0c28\u0c26\u0c3f \u0c05\u0c2d\u0c3f\u0c2a\u0c4d\u0c30\u0c3e\u0c02\u0c1a\u0c3f \u0c35\u0c28\u0c4d\u0c28\u0c40 \u0c30\u0c4b\u0c1c\u0c41\u0c32\u0c35\u0c3e\u0c21\u0c3f \u0c1a\u0c40\u0c35\u0c4d\u0c2e\u0c46\u0c02\u0c24\u0c02\u0c26\u0c32\u0c41 \u0c05\u0c02'
   ALN: ''
   OUT: u'\xbb'
1 315.51 (707, 48) ../samples/0005.png
   TRU: u'\u0c35\u0c02 \u0c32\u0c47\u0c2c\u0c21\u0c3f\u0c2f\u0c3e\u0c30\u0c2a\u0c28\u0c3f\u0c2e\u0c3e\u0c30\u0c41 \u0c28\u0c47 \u0c26\u0c43\u0c37\u0c4d\u0c1f\u0c3f\u0c38\u0c3e\u0c30\u0c41\u0c32\u0c3e\u0c02 \u0c06\u0c26\u0c4d\u0c2f\u0c02 \u0c05\u0c35\u0c30\u0c4b'
   ALN: ''
   OUT: u'8'
2 305.20 (695, 48) ../samples/0000.png
   TRU: u'\u0c07\u0c02\u0c26\u0c3f \u0c15\u0c3e\u0c28\u0c3f\u0c2e\u0c41\u0c1f\u0c4d\u0c1f\u0c3f \u0c09\u0c28\u0c4d\u0c2e\u0c3e\u0c26\u0c41 \u0c15\u0c4a\u0c02\u0c1f\u0c47 \u0c28\u0c41\u0c02\u0c26\u0c41\u0c15\u0c46\u0c21\u0c41 \u0c38\u0c39\u0c23 \u0c2c\u0c4a\u0c2e\u0c4d\u0c2e\u0c30\u0c3f'
   ALN: ''
   OUT: '~'
```

While training, the output is just `~` and it fails with 

```
8069 67.40 (681, 48) ../samples/0002.png
   TRU: u'\u0c2f\u0c41\u0c35\u0c28\u0c26\u0c3f \u0c05\u0c2d\u0c3f\u0c2a\u0c4d\u0c30\u0c3e\u0c02\u0c1a\u0c3f \u0c35\u0c28\u0c4d\u0c28\u0c40 \u0c30\u0c4b\u0c1c\u0c41\u0c32\u0c35\u0c3e\u0c21\u0c3f \u0c1a\u0c40\u0c35\u0c4d\u0c2e\u0c46\u0c02\u0c24\u0c02\u0c26\u0c32\u0c41 \u0c05\u0c02'
   ALN: '~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
   OUT: '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
8070 67.91 (615, 48) ../samples/0009.png
   TRU: u'\u0c15\u0c3e\u0c30\u0c32\u0c28\u0c3f \u0c07\u0c15\u0c4d\u0c15\u0c21\u0c3f \u0c38\u0c3e\u0c32\u0c4d\u0c32\u0c4b \u0c2c\u0c3e\u0c27\u0c4d\u0c2f \u0c15\u0c4a\u0c26\u0c4d\u0c26\u0c3f\u0c2e\u0c28\u0c35\u0c21\u0c02\u0c17\u0c3e \u0c35\u0c3f\u0c37\u0c3e \u0c1c\u0c42\u0c38\u0c3f'
   ALN: '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~ ~~~~~~~~~~~'
   OUT: '~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~'
# oops, got FloatingPointError overflow encountered in exp
Traceback (most recent call last):
  File "ocropus-rtrain", line 287, in <module>
    pcs = network.trainSequence(line,cs,update=do_update,key=fname)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 894, in trainSequence
    self.outputs = array(self.lstm.forward(xs))
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 606, in forward
    xs = net.forward(xs)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 662, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 560, in forward
    self.WIP,self.WFP,self.WOP)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 429, in forward_py
    go[t] = ffunc(gox[t])
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 377, in ffunc
    return 1.0/(1.0+exp(-x))
FloatingPointError: overflow encountered in exp
Traceback (most recent call last):
  File "ocropus-rtrain", line 291, in <module>
    network = load_lstm(last_save)
  File "ocropus-rtrain", line 177, in load_lstm
    network = ocrolib.load_object(last_save)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/common.py", line 501, in load_object
    fname = ocropus_find_file(fname)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/common.py", line 714, in ocropus_find_file
    full = os.path.join(prefix, basename, fname)
  File "/usr/lib/python2.7/posixpath.py", line 68, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Any help on how to fix this?

**Comment by zuphilip** [comment]
> When training starts it is doesn't include telugu language

You need to specify the codec, if you don't want to use the default one. I think the easiest is to use the `-c` option to construct the codec from the ground truth data.

Maybe the `FloatingPointError` will then also not appear...

( It looks that you now also tried kraken and receive different errors there: https://github.com/mittagessen/kraken/issues/32 )

**Comment by ChillarAnand** [comment]
As you mentioned, i have created a text file with this line

```
 ఁంఃఅఆఇఈఉఊఋఌఎఏఐఒఓఔకఖగఘఙచఛజఝఞటఠడఢణతథదధనపఫబభమయరఱలళవశషసహఽాిీుూృౄెేైొోౌ్ౘౙౠౡౢౣ౦౧౨౩౪౫౬౭౮౯
```

and supplied it with `-c c.txt` and it is working fine.

Thanks @zuphilip

**Comment by ChillarAnand** [comment]
`FloatingPointError` still occurs once in a while

```
# oops, got FloatingPointError overflow encountered in exp
Traceback (most recent call last):
  File "ocropus-rtrain", line 287, in <module>
    pcs = network.trainSequence(line,cs,update=do_update,key=fname)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 894, in trainSequence
    self.outputs = array(self.lstm.forward(xs))
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 606, in forward
    xs = net.forward(xs)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 662, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 560, in forward
    self.WIP,self.WFP,self.WOP)
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 429, in forward_py
    go[t] = ffunc(gox[t])
  File "/home/chillaranand/projects/python/ocr/ocropy/ocrolib/lstm.py", line 377, in ffunc
    return 1.0/(1.0+exp(-x))
FloatingPointError: overflow encountered in exp
```

**Comment by harinath141** [comment]
Hi @ChillarAnand I have seen your training set,
It perfect for training but my training set is different The consonants and vowels are not binding together its displaying separately.
Have you done any processing or code changes.
Also what the progress of your training in telugu If so kindly can you share the model in dropbox link???
Thanks in advance.

**Comment by ChillarAnand** [comment]
@harinath141,  Telugu [model is here](https://www.dropbox.com/sh/nog97gyianhqxqf/AABDOh_8Uq6YnG1EQCzVmHbna). I wrote a script to generate training data. I have to make some more changes and I will publish it soon.

Regarding progress, I have trained model with 200,000 lines with 30 chars each. However the accuracy is still ~70%.

I am new to nueral networks and I am not sure what the problem is. I am suspecting the problem might be with training data itself. I need to tweak training data and then train once again. I am trying to OCR several books. So, I am trying to get 95%+ accuracy.

**Comment by zuphilip** [comment]
Some other models are already shared somewhere on GitHub and we collected the links here on the wiki: https://github.com/tmbdev/ocropy/wiki/Models . If you have anything you want to share not only temporarily, then it would be nice if you would add your model there as well (everybody should be able to write on the wiki pages).

**Comment by ChillarAnand** [comment]
Added to wiki. Thanks @zuphilip

**Comment by harinath141** [comment]
@ChillarAnand can you provide more data for training??
My problem is mentioned in #169 issue kindly look in to that if you can solve. I have seen your training data it's good how you did that

**Comment by ChillarAnand** [comment]
@harinath141  Training data is huge. You can use this wrapper [script to generate data](https://github.com/ChillarAnand/01/blob/master/python/ocr_training_data.py)

    python ocr_training_data.py /path/to/output 1000000

We can take discussion offline as this might be not relevant here.
