### ISSUE TITLE
Error while running ocropus-nlbin in Ubuntu 16.04 (64bit version)

### ISSUE THREAD

**Issue by deepnirmal** [tmbdev/ocropy#192]
```
Traceback (most recent call last):
  File "./ocropus-nlbin", line 10, in <module>
    import ocrolib
  File "/home/deep2432/Desktop/ocropy/ocrolib/__init__.py", line 12, in <module>
    from common import *
  File "/home/deep2432/Desktop/ocropy/ocrolib/common.py", line 18, in <module>
    import lstm
  File "/home/deep2432/Desktop/ocropy/ocrolib/lstm.py", line 32, in <module>
    import nutils
  File "/home/deep2432/Desktop/ocropy/ocrolib/nutils.py", line 25, in <module>
    lstm_native = compile_and_load(lstm_utils)
  File "/home/deep2432/Desktop/ocropy/ocrolib/native.py", line 68, in compile_and_load
    return ctypes.CDLL(path)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: .pynative/cccd32009099f8dade0fe6cd205bf188.so: wrong ELF class: ELFCLASS32

```

Please help this is a serious problem I'm facing since 10 days. I have tried adding 32bit architecture and other libraries which is required to run 32bit packages.

**Comment by zuphilip** [comment]
Did you have ocropy running before on your machine or this is new installation?

I just tried ocropy on a new ubuntu 16.04 (docker container) and everything looks fine.

**Comment by deepnirmal** [comment]
Yes its working now! I didn't clone the newer version of setup files. Working properly now. 
Those who get this kind of error or any ELF class error pls also refer to  http://unix.stackexchange.com/questions/12956/how-do-i-run-32-bit-programs-on-a-64-bit-debian-ubuntu
Thanks @zuphilip 👍
