### ISSUE TITLE
IndexError: string index out of range Error!!!

### ISSUE THREAD

**Issue by AzkaGilani** [tmbdev/ocropy#212]
I am using ocropus for extracting text from the image. But it throws an error when box of the image contains uni-code characters.. Corresponding text file is empty. and then suddenly it gives following error:
```
INFO:  /tmp/price-right/ocropy/d1ebf174-48ce-4cf6-bec1-0272ab211785/8.png:O7- JUN-16
INFO:  /tmp/price-right/ocropy/d1ebf174-48ce-4cf6-bec1-0272ab211785/30.png:
Traceback (most recent call last):
  File "/home/azka/CameraApp/ocropy/ocropus-rpred", line 205, in <module>
    result.append(process1((trial,path+fname)))
  File "/home/azka/CameraApp/ocropy/ocropus-rpred", line 185, in process1
    ocrolib.write_text(base+".txt",pred)
  File "/home/azka/CameraApp/ocropy/ocrolib/common.py", line 105, in write_text
    if not nonl and text[-1]!='\n':
IndexError: string index out of range


How can i resolve this?

```

**Comment by zuphilip** [comment]
What is the exact command you are using and which image(s) do you have for input?

**Comment by zuphilip** [comment]
Closing this issue because of inactivity. If the problem remains, then feel free to reopen it.

**Comment by rnsrk** [comment]
I'm handling with the same problem, I opened a new thread with more detailed information: https://github.com/tmbdev/ocropy/issues/243
