### ISSUE TITLE
RuntimeError: could not open display

### ISSUE THREAD

**Issue by vlad-wonderkidstudio** [tmbdev/ocropy#226]
After installed on the command line CentOS server, when I try to run any OCRopus command, I get the following error:

 ```
$ ./ocropus-nlbin -h
Traceback (most recent call last):
  File "./ocropus-nlbin", line 5, in <module>
    from pylab import *
  File "/usr/lib64/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/lib64/python2.7/site-packages/matplotlib/pylab.py", line 265, in <module>
    from matplotlib.pyplot import *
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 97, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 13, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display

```
## Expected Behavior

On my home Ubuntu within Gnome command line it works just fine.

## Steps to Reproduce (for bugs)

1. Install on CentOS command-line only server (without display)
2. Run any command, like $ ./ocropus-nlbin -h
3. Get the error

## Your Environment

* Python version: 2.7.5

* Git revision of ocropy: 
commit 358df8d104cf78fb0104bd28f333f272d908d4c3
Merge: dacf0fc e016e74
Author: Philipp Zumstein <zuphilip@users.noreply.github.com>
Date:   Mon May 22 22:38:33 2017 +0200

    Merge pull request #219 from tmbdev/del-bbox-func

    Delete unused function bounding_box in ocropus-linegen

* Operating System and version:
CentOS Linux release 7.3.1611 (Core)

**Comment by zuphilip** [comment]
The error looks like the display is not found for matplot, and indeed you write that you are using ocropy on the *command line* CentOS server. You can try to set `export MPLBACKEND="agg"` as it is also done in the [CircleCI file](https://github.com/tmbdev/ocropy/blob/master/circle.yml#L5-L6).

**Comment by vlad-wonderkidstudio** [comment]
I tried to do so. After this I launched:
./ocropus-nlbin -h
And it just hangs (I can type texts in the console and anything, but no answer from the program).
After I pressed CTRL+C I got this message:

Traceback (most recent call last):
  File "./ocropus-nlbin", line 5, in <module>
    from pylab import *
  File "/usr/lib64/python2.7/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 151, in <module>
    from matplotlib.rcsetup import (defaultParams,
  File "/usr/lib64/python2.7/site-packages/matplotlib/rcsetup.py", line 20, in <module>
    from matplotlib.colors import is_color_like
  File "/usr/lib64/python2.7/site-packages/matplotlib/colors.py", line 52, in <module>
    import numpy as np
  File "/usr/lib64/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    import polynomial
  File "/usr/lib64/python2.7/site-packages/numpy/polynomial/__init__.py", line 18, in <module>
    from polynomial import Polynomial
  File "/usr/lib64/python2.7/site-packages/numpy/polynomial/polynomial.py", line 54, in <module>
    """
KeyboardInterrupt

**Comment by zuphilip** [comment]
Hm... I have no experience with CentOS. Maybe @kba has some ideas?

**Comment by kba** [comment]
Hard to say w/o running a CentOS image. numpy/scipy/matplotlib can be tricky at times because of location of compiled libs etc.

Maybe run ocropus w/ docker?

**Comment by stweil** [comment]
Isn't it normal behaviour that no display is found if you run on a host which only has command line installed? If I have a program which requires a display I'd install display support (for example X Windows on Linux).

**Comment by kba** [comment]
> Isn't it normal behavior that no display is found if you run on a host which only has command line installed? 

That was the initial issue, solved by setting Matplotlib's backend. [The second issue](https://github.com/tmbdev/ocropy/issues/226#issuecomment-308373438) is something different.

**Comment by vlad-wonderkidstudio** [comment]
@kba 
How can I run it with docker?

**Comment by zuphilip** [comment]
You can use this docker image: https://hub.docker.com/r/kbai/ocropy/

**Comment by zuphilip** [comment]
@vlad-wonderkidstudio Did you find a solution for your CentOS?
