### ISSUE TITLE
Unable to run binarization 

### ISSUE THREAD

**Issue by SaikrishnaViridis** [tmbdev/ocropy#253]
## Expected Behavior
Unable to run ocropus-nlbin

## Current Behavior
IM-LP-577:Downloads sbachu$ ocropus-nlbin test.JPG -o output
clang: warning: -O4 is equivalent to -O3
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-nlbin", line 15, in <module>
    import ocrolib
  File "/usr/local/lib/python2.7/site-packages/ocrolib/__init__.py", line 12, in <module>
    from common import *
  File "/usr/local/lib/python2.7/site-packages/ocrolib/common.py", line 34, in <module>
    import lstm
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 38, in <module>
    import nutils
  File "/usr/local/lib/python2.7/site-packages/ocrolib/nutils.py", line 25, in <module>
    lstm_native = compile_and_load(lstm_utils)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/native.py", line 69, in compile_and_load
    path = compile_and_find(c_string,**keys)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/native.py", line 65, in compile_and_find
    raise CompileError()
ocrolib.native.CompileError

## Steps to Reproduce (for bugs)
1. goto repo folder 
2. ocropus-nlbin test.JPG -o output

## Your Environment

* Python version: Python 2.7.14

* Git revision of ocropy: 
commit d823ba4f4aaa6b85a19804e4569fe86a4be3f0d4
Merge: 5027794 8f354ad
Author: Konstantin Baierer <kba@users.noreply.github.com>
Date:   Fri Sep 29 16:19:54 2017 +0200

    Merge pull request #206 from zuphilip/imports
    
    Standardize Imports I, #176

* Operating System and version: Mac OS Sierra

**Comment by kba** [comment]
```
clang: error: unsupported option '-fopenmp'
```

OSX's bundled clang doesn't have OpenMP support enabled apparently. I don't have a Mac so I can't help you with that, but googleing `macosx clang opnmp` shows a few SO answers to that.

**Comment by amitdo** [comment]
https://github.com/tmbdev/ocropy/blob/97ace5581b/README_OSX.md

**Comment by zuphilip** [comment]
Closing this, because the native code is not anymore needed #265. Update your repository and try again.
