### ISSUE TITLE
Mean of empty slice error?

### ISSUE THREAD

**Issue by gjerome5** [tmbdev/ocropy#297]
Can any one tell me, while creating a training model the below error is triggering.....so please kindly provide me the solution.. 
```
C:\Python27\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
Traceback (most recent call last):
  File "ocropus-rtrain", line 293, in <module>
    network.lnorm.measure(np.amax(line)-line)
  File "C:\Users\jenova jasmine\Desktop\ocropy-master\ocrolib\lineest.py", line 38, in measure
    self.mad = mean(deltas[line!=0])
  File "C:\Python27\lib\site-packages\numpy\core\fromnumeric.py", line 2957, in mean
    out=out, **kwargs)
  File "C:\Python27\lib\site-packages\numpy\core\_methods.py", line 80, in _mean
    ret = ret.dtype.type(ret / rcount)
FloatingPointError: invalid value encountered in double_scalars
```
Environment Setup
* Python version: 2.7

* Git revision of ocropy: 
* Operating System and version: windows 7

**Comment by zuphilip** [comment]
What command did you use for training? Besides the warning there is also a FloatingPointError... Do you see this immediately or is the training process working for a while? Does the `./run-rtrain` work?

**Comment by zuphilip** [comment]
Closing this issue because of inactivity. If the problem remains, then feel free to reopen it.
