### ISSUE TITLE
Installing on Mac OS El Capitan

### ISSUE THREAD

**Issue by tim401** [tmbdev/ocropy#308]
## Current Behavior
When installing on OS X El Capitan the installation fails because of the [System Integrity Protection (SIP)](https://support.apple.com/en-us/HT204899) with the following error:
`changing mode of /usr/local/bin/ocropus-visualize-results to 755
running install_data
creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
`

## Possible Solution

I could temporarily disable SIP, but that doesn't seem like a good idea. I tried temporarily removing sip from the needed files, but when booting into recovery mode they aren't even loaded and available to remove the restricted flag.

[brew](https://brew.sh) is a possible solution, but there are no packages for matplotlib or lxml.

## Steps to Reproduce (for bugs)

1. Installed new clean copy of MacPorts and updated it
2. sudo port install py27-scipy py27-matplotlib py27-lxml
3. curl -O http://www.tmbdev.net/en-default.pyrnn.gz
4. mv en-default.pyrnn.gz models/
5. sudo python setup.py install

## Your Environment

* Python version:
Python 2.7.10

* Git revision of ocropy: 
fatal: Not a git repository (or any of the parent directories): .git
I downloaded the code with the last revision date Feb 19
* Operating System and version:
Mac OS El Capitan 10.11

**Comment by zuphilip** [comment]
Do I understand correctly that just the last step `setup python setup.py install` does not work? If yes, then you can also try to start the ocropus-commands directly, i.e. `./ocropus-nlbin` etc. Does this work?

**Comment by tim401** [comment]
Yes that is correct, just the last step fails. But when I call the command directly I get different errors.

./ocropus-nlbin tests/ersch.png -o book
Traceback (most recent call last):
  File "./ocropus-nlbin", line 15, in <module>
    import ocrolib
  File "/Users/user/ocropy-master/ocrolib/__init__.py", line 14, in <module>
    from common import *
  File "/Users/user/ocropy-master/ocrolib/common.py", line 26, in <module>
    import PIL
ImportError: No module named PIL

**Comment by zuphilip** [comment]
Okay, you need also the Python packages from `requirements.txt`. Install with
```
pip install -r requirements.txt
```
or
```
conda install --file requirements.txt
```

**Comment by tim401** [comment]
Alright, I don't have either pip or condo but I used macports to install the two packages that are listed in the requirements file but not in the PACKAGES file by the following:
sudo port install py27-Pillow py27-numpy
But I still get the exact same error as above, including the last line ImportError: No module named PIL

Pillow is obviously supposed to be a fork of PIL, but it doesn't seem to be cooperating.

I also get the same error if I uninstall Pillow and install py27-pil.

**Comment by zuphilip** [comment]
You need to install these packages within python and macports is only installing packages within your system. Try to install pip (or conda) first and then proceed with the line above.

**Comment by zuphilip** [comment]
Closing this issue because of inactivity. @tim401 If the problem remains, then feel free to reopen it.
