### ISSUE TITLE
Possible bug in ocropus-rtrain

### ISSUE THREAD

**Issue by adnanulhasan** [tmbdev/ocropy#36]
During the training, an exception is raised if 'floating point error' occurs. The script (ocropus-rtrain) then loads the previous model using lstm_load(last_save) (line 289 in ocropus-rtrain). 
Now, if the floating point error is raised during the first mini-batch, there is no model found, as last_save is still None. The result is:

Traceback (most recent call last):
  File "../ocropy/ocropus-rtrain", line 313, in <module>
    network = load_lstm(last_save)
  File "../ocropy/ocropus-rtrain", line 191, in load_lstm
    network = ocrolib.load_object(last_save)
  File "/export/home/adnan/ocropy/ocrolib/common.py", line 503, in load_object
    fname = ocropus_find_file(fname)
  File "/export/home/adnan/ocropy/ocrolib/common.py", line 682, in ocropus_find_file
    if os.path.exists(fname):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

In this case, there should be a way to restart the training.

**Comment by tmbdev** [comment]
I'm adding a check for last_save being None. I think generally, if you get a floating point error during the first round, the learning rate is so wrong that restarting isn't very useful.

**Comment by kba** [comment]
Was that check implemented? I cannot find it in the commit history.

**Comment by Luonic** [comment]
Looks like i having same problem, Mac OS X El Capitan
```
# oops, got FloatingPointError overflow encountered in exp
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rtrain", line 286, in <module>
    pcs = network.trainSequence(line,cs,update=do_update,key=fname)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 890, in trainSequence
    self.outputs = array(self.lstm.forward(xs))
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 605, in forward
    xs = net.forward(xs)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 661, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 640, in forward
    return self.net.forward(xs[::-1])[::-1]
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 559, in forward
    self.WIP,self.WFP,self.WOP)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 428, in forward_py
    go[t] = ffunc(gox[t])
  File "/usr/local/lib/python2.7/site-packages/ocrolib/lstm.py", line 376, in funk
    return 1.0/(1.0+exp(-x))
FloatingPointError: overflow encountered in exp
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rtrain", line 290, in <module>
    network = load_lstm(last_save)
  File "/usr/local/bin/ocropus-rtrain", line 176, in load_lstm
    network = ocrolib.load_object(last_save)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/common.py", line 503, in load_object
    fname = ocropus_find_file(name)
  File "/usr/local/lib/python2.7/site-packages/ocrolib/common.py", line 682, in ocropus_find_file
    if os.path.exists(name):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by kba** [comment]
@Luonic Can you create a new issue, ideally with the data to reproduce the problem? This seems a fixable bug.
