### ISSUE TITLE
Error in ocropus-econf with some k-options

### ISSUE THREAD

**Issue by zuphilip** [tmbdev/ocropy#45]
The function `ocropus-econf` returns an error when comparisons should only be done among the `letters` or `digits`, i.e.

```
$ ocropus-econf -k digits output/*/*.gt.txt
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-econf", line 59, in <module>
    outputs = sorted(list(outputs))
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 560, in parallel_map
    result = fun(e)
  File "/usr/local/bin/ocropus-econf", line 50, in process1
    err,cs = edist.xlevenshtein(txt,gt,context=args.context)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/edist.py", line 43, in xlevenshtein
    cost = current[n]
UnboundLocalError: local variable 'current' referenced before assignment
```

**Comment by zuphilip** [comment]
Okay, it seems that the function <a href="https://github.com/tmbdev/ocropy/blob/master/ocrolib/edist.py#L20">`xlevenshtein(a,b,context=1)`</a> is not yet covering the boundary cases:
   1. `a="", b=""` --> I guess we can simply catch that case in the beginning and output the correct thing, maybe `return 0,[]`
   2. `a=/="", b=""` --> Maybe, the simplest would be to call `xlevenshtein(b,a,context=1)`. Then the cost should be the same and we just have to swap each entry of the confusion matrix list.

**Comment by zuphilip** [comment]
The implementation in hocr-tools looks different and it seems to exactly deal also with these cases: https://github.com/tmbdev/hocr-tools/blob/master/hocr-eval-lines#L36-L57
