### ISSUE TITLE
TypeError: dot() takes no keyword arguments

### ISSUE THREAD

**Issue by tzbb1234** [tmbdev/ocropy#56]
when I execute ./run-test and ./run-rtrain commands, appear below error, please check and help me:

TypeError: dot() takes no keyword arguments
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rpred", line 245, in safe_process1
    return process1(arg)
  File "/usr/local/bin/ocropus-rpred", line 150, in process1
    pred = network.predictString(line)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 934, in predictString
    cs = self.predictSequence(xs)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 884, in predictSequence
    self.outputs = array(self.lstm.forward(xs))
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 605, in forward
    xs = net.forward(xs)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 661, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 559, in forward
    self.WIP,self.WFP,self.WOP)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 414, in forward_py
    dot(WGI,source[t],out=gix[t])

execute ./run-rtrain, error message as below:

$ ./run-rtrain 
+ tar -zxf tests/uw3-500.tgz
+ ocropus-rtrain 'book/*/*.bin.png' -d 5 -o uw3-500-model
# inputs 500
# tests None
# CenterNormalizer
# using default codec
# charset size 157 [ ~!"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}隆垄拢搂漏芦庐掳露禄驴妹?
                                                            妹妹妹妹妹妹妹犆⒚っγ┟疵睹访姑幻济颗排糕犫♀⑩ｂ光衡猹猥猞]
# last_trial 0
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rtrain", line 285, in <module>
    pcs = network.trainSequence(line,cs,update=do_update,key=fname)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 890, in trainSequence
    self.outputs = array(self.lstm.forward(xs))
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 605, in forward
    xs = net.forward(xs)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 661, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 559, in forward
    self.WIP,self.WFP,self.WOP)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 414, in forward_py
    dot(WGI,source[t],out=gix[t])
TypeError: dot() takes no keyword arguments

**Comment by tzbb1234** [comment]
because numpy version is incorrect, execute:
sudo pip uninstall numpy
sudo pip install numpy upgrade

is OK!
