### ISSUE TITLE
pylab.uint32 error (ubuntu 14.04)

### ISSUE THREAD

**Issue by Munawwar** [tmbdev/ocropy#63]
Hi. I tried installing the dependencies using pip on master and ran tests (on Ubuntu 14.04.2 LTS), and I get `ImportError: cannot import name uint32` (full stack trace at the bottom). I also tried installing exact versions as in requirement_1.txt, yet no luck.

I checked out v1.0, removed pip libs and did aptitude install of the dependencies and still get the same error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-nlbin", line 9, in <module>
    import ocrolib
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/__init__.py", line 12, in <module>
    from common import *
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 16, in <module>
    import ligatures
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/ligatures.py", line 8, in <module>
    from pylab import uint32
ImportError: cannot import name uint32
```
What do you think is wrong?

**Comment by Munawwar** [comment]
I installed everything on a clean Ubuntu and things started working. Not sure what went wrong there.

**Comment by MordFee** [comment]
Hi,

I'm having the same problem with ubuntu 16.04.
I tried reinstalling everything just like Munawwar, but it doesn't help.
I'm not using a virtualenv either

Thanks for any insight

**Comment by MordFee** [comment]
I found where my error came from : 
if I install opencv & ocropy -> it's working fine
if I re-install pylab package -> it's crashing

**Comment by traims** [comment]
The same issue on Mac OS X Yosemite. 


pylab==0.1.3

numpy==1.11.1
scipy==0.18.1
matplotlib==1.5.3
beautifulsoup4==4.5.1
numexpr==2.6.1
Cython==0.24.1
Pillow==3.3.1
tables==3.3.0


```
$ ./run-test
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-nlbin", line 10, in <module>
    import ocrolib
  File "/usr/local/lib/python2.7/site-packages/ocrolib/__init__.py", line 12, in <module>
    from common import *
  File "/usr/local/lib/python2.7/site-packages/ocrolib/common.py", line 16, in <module>
    import ligatures
  File "/usr/local/lib/python2.7/site-packages/ocrolib/ligatures.py", line 8, in <module>
    from pylab import uint32
ImportError: cannot import name uint32
```

**Comment by QuLogic** [comment]
The `pylab` that ocropy wants is the meta import-the-world-and-shouldn't-be-used-anymore package in `matplotlib`; the `pylab` you have installed is some imposter.

**Comment by kba** [comment]
I don't have a Mac and can't reproduce this on Linux, but I suspect this should import `dtype.uint32` from `numpy`, grep the code for `uint32` to see how it is used in other places.

To get up and running without installing gcc and python modules., you could try the [ocropy docker](https://github.com/kba/docker-ocropy) container.
