### ISSUE TITLE
program crashed after I run test

### ISSUE THREAD

**Issue by Halfish** [tmbdev/ocropy#81]
After I install the ocropy, I just run the test on my Ubuntu 15.04 like this, 
```python
./run-test
```
Then the program just crashed and give me the message like this,
```python
INFO:  #tests/testpage.png
INFO:  === tests/testpage.png 1
INFO:  estimating skew angle
INFO:  estimating thresholds
INFO:  rescaling
INFO:  tests/testpage.png lo-hi (0.39 1.44) angle  0.1 no-normalization
INFO:  writing
INFO:  
INFO:  ########## /usr/local/bin/ocropus-gpageseg temp/????.bin.png
INFO:  
INFO:  temp/0001.bin.png
INFO:  scale 19.4935886896
INFO:  computing segmentation
INFO:  computing column separators
INFO:  computing lines
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-gpageseg", line 423, in safe_process1
    process1(job)
  File "/usr/local/bin/ocropus-gpageseg", line 379, in process1
    segmentation = compute_segmentation(binary,scale)
  File "/usr/local/bin/ocropus-gpageseg", line 314, in compute_segmentation
    seeds = compute_line_seeds(binary,bottom,top,colseps,scale)
  File "/usr/local/bin/ocropus-gpageseg", line 263, in compute_line_seeds
    bmarked *= (bottom>t*amax(bottom)*t)*(1-colseps)
TypeError: Cannot cast ufunc multiply output from dtype('int32') to dtype('bool') with casting rule 'same_kind'
INFO:  
INFO:  ########## /usr/local/bin/ocropus-rpred -n temp/????/??????.bin.png
INFO:  
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rpred", line 98, in <module>
    inputs = ocrolib.glob_all(args.files)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/toplevel.py", line 213, in argument_checks
    result = f(*args,**kw)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 654, in glob_all
    raise FileNotFound("%s: expansion did not yield any files"%arg)
ocrolib.common.FileNotFound: file not found temp/????/??????.bin.png: expansion did not yield any files
```

How can I fix this? Thanks.

**Comment by QuLogic** [comment]
See #75.

**Comment by Halfish** [comment]
Thanks to @QuLogic , I just fixed it myself just now. I forcely change the numpy array from 'int32' to 'bool' by add `.astype('bool')`
