### ISSUE TITLE
Probabilities not working on trained model 

### ISSUE THREAD

**Issue by 1a1a11a** [tmbdev/ocropy#90]
when I use zuphilip's branch on OCR with pre-trained model, it will report error, see following. How can I fix that? @zuphilip 

```
Traceback (most recent call last):
  File "./ocropus-rpred", line 253, in safe_process1
    return process1(arg)
  File "./ocropus-rpred", line 148, in process1
    pred = network.predictString(line)
  File "/root/Michael/ocropy/ocrolib/lstm.py", line 926, in predictString
    cs = self.predictSequence(xs)
  File "/root/Michael/ocropy/ocrolib/lstm.py", line 876, in predictSequence
    self.outputs = array(self.lstm.forward(xs))
  File "/root/Michael/ocropy/ocrolib/lstm.py", line 587, in forward
    xs = net.forward(xs)
  File "/root/Michael/ocropy/ocrolib/lstm.py", line 636, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/root/Michael/ocropy/ocrolib/lstm.py", line 537, in forward
    if n>N: raise ocrolib.RecognitionError("input too large for LSTM model")
RecognitionError: input too large for LSTM model
```

**Comment by zuphilip** [comment]
Do you have more details here? It doesn't look that this is related to the new function `translate_back_with_probabilities` which would be on the [lines 756-772](https://github.com/zuphilip/ocropy/blob/c28e0263f321402c9a8e5600ee177b5bafb944cc/ocrolib/lstm.py#L756-L772). Actually, the error report points to line 537 but the raise would be in [line 551](https://github.com/zuphilip/ocropy/blob/master/ocrolib/lstm.py#L551). Which branch are you using?

(BTW If this issue is not anymore relevant for you, we can also close the issue.)

**Comment by kba** [comment]
There's not enough information in here. @1a1a11a Please try again with #135 and open a new issue if you encounter problems.
