### ISSUE TITLE
Error in ocropus-rtrain

### ISSUE THREAD

**Issue by anupamaray** [tmbdev/ocropy#93]
I am trying to use ocropus-rtrain: ocropus-rtrain -o model try/*.bin.png
At the begining itself I am getting this error (I am using Ubuntu ans all images with gt.txt files are in try folder)

`# oops, got FloatingPointError divide by zero encountered in double_scalars
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rtrain", line 286, in <module>
    pcs = network.trainSequence(line,cs,update=do_update,key=fname)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/lstm.py", line 902, in trainSequence
    self.error_log.append(self.error**.5/len(cs))
FloatingPointError: divide by zero encountered in double_scalars
Traceback (most recent call last):
  File "/usr/local/bin/ocropus-rtrain", line 290, in <module>
    network = load_lstm(last_save)
  File "/usr/local/bin/ocropus-rtrain", line 176, in load_lstm
    network = ocrolib.load_object(last_save)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 503, in load_object
    fname = ocropus_find_file(fname)
  File "/usr/local/lib/python2.7/dist-packages/ocrolib/common.py", line 682, in ocropus_find_file
    if os.path.exists(fname):
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found`

 Can someone help with this error?
@kba please let me know if some mode detail would help.  I have sample data, command lines and model files if they would helpful.

**Comment by kba** [comment]
The problem is in `ocropus-rtrain`, line 248

```python
     cs = array(codec.encode(transcript),'i')
```

If cs has zero length, this will lead to a division by zero in `ocrolib/lstm.py`, line 902:

```python
        self.error_log.append(self.error**.5/len(cs))
```

The problem is `transcript`, which is loaded in line `ocropus-rtrain`, line 263:

```python
    base,_ = ocrolib.allsplitext(fname)
    try:
        line = ocrolib.read_image_gray(fname)
        transcript = ocrolib.read_text(base+".gt.txt")   ### <- HERE
    except IOError as e:
        print "ERROR",e
        continue
```

Are you sure your transcripts (`*.gt.txt`) are there and not empty?

**Comment by anupamaray** [comment]
thank you @kba .. I have checked the transcripts..   for 30000 images it is throwing an error: `argument list too long`
for 500 images it is working but got stuck: 
`8994 16.31 (110, 48) try/Sukat_WN-P7a_r49_4242-148-4551-254_9.bin.png
   TRU: u'1B32 1B38 1B13 1B22'
   ALN: u'1B32 1B38 B133 B'
   OUT: u'1B21111'`
Any idea why so.. I am running ocropus-rtrain -o model try/*.bin.png
Could you tell me what  8994 signifies

**Comment by kba** [comment]
> for 30000 images it is throwing an error: argument list too long

You should avoid providing too much input, "over-learning" can actually degrade the recognition. I don't have good estimates about good numbers though. @zuphilip @jze ?

The `argument list too long` is a limitation of your shell.

> Could you tell me what 8994 signifies

8994 is the current iteration. That print statement is produced in line 298ff of `ocropus-rtrain`:

```python
        print "%d %.2f %s"%(trial,network.error,line.shape),fname
        print "   TRU:",repr(transcript)
        print "   ALN:",repr(gta[:len(transcript)+5])
        print "   OUT:",repr(pred[:len(transcript)+5])
```

**Comment by zuphilip** [comment]
Dan @danvk wrote a very interesting blog post about training ocropus: http://www.danvk.org/2015/01/11/training-an-ocropus-ocr-model.html . He used in one experiment _400 lines_ and in the other _800 lines_. Another person is training some Asian symbols with _2000 lines_: https://github.com/tmbdev/ocropy/issues/54#issuecomment-145747611

**Comment by wanghaisheng** [comment]
the same issue  
```

6282 13.41 (116, 48) trainning_data/pic_simsun/016781.bin.png
   TRU: u'\u88815212'
   ALN: u'~22'
   OUT: '~~'
6283 12.15 (122, 48) trainning_data/pic_simsun/010265.bin.png
   TRU: u'\u8db18485'
   ALN: u'~8855'
   OUT: '~~'
6284 15.23 (119, 48) trainning_data/pic_simsun/012939.bin.png
   TRU: u'\u70753373'
   ALN: u'~3333'
   OUT: '~~'
/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
Traceback (most recent call last):
  File "ocropus-rtrain", line 275, in <module>
    network.lnorm.measure(amax(line)-line)
  File "/ocropy/ocrolib/lineest.py", line 43, in measure
    self.mad = mean(deltas[line!=0])
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2716, in mean
    out=out, keepdims=keepdims)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 67, in _mean
    ret = ret.dtype.type(ret / rcount)
FloatingPointError: invalid value encountered in double_scalars

```

```
python ocropus-rtrain -o report trainning_data/pic_simsun/*.bin.png -S  800

```

 ocropus-rtrain changed as @kba suggested 
```

root@4b2648975d03:/ocropy# cat ocropus-rtrain
#!/usr/bin/env python
# vim: set fileencoding=utf8 :

import sys
import random as pyrandom
import re
from pylab import *
import os.path
import ocrolib
import argparse
import matplotlib
import numpy
from ocrolib import lineest
import ocrolib.lstm as lstm
import traceback

numpy.seterr(divide='raise',over='raise',invalid='raise',under='ignore')

reload(sys)
sys.setdefaultencoding('utf-8')
parser = argparse.ArgumentParser("train an RNN recognizer")

# line normalization
parser.add_argument("-e","--lineest",default="center",
                    help="type of text line estimator, default: %(default)s")
parser.add_argument("-E","--nolineest",action="store_true",
                    help="don't perform line estimation and load .dew.png file")
parser.add_argument("-l","--height",default=48,type=int,
                    help="set the default height for line estimation, default: %(default)s")
parser.add_argument("--dewarp",action="store_true",
                    help="only perform line estimation and output .dew.png file")

# character set
parser.add_argument("-c","--codec",default=[],nargs='*',
                    help="construct a codec from the input text")

# learning
parser.add_argument("-C","--clstm",action="store_true",
                    help="use C++ LSTM")
parser.add_argument("-r","--lrate",type=float,default=1e-4,
                    help="LSTM learning rate, default: %(default)s")
parser.add_argument("-S","--hiddensize",type=int,default=100,
                    help="# LSTM state units, default: %(default)s")
parser.add_argument("-o","--output",default=None,
                    help="LSTM model file")
parser.add_argument("-F","--savefreq",type=int,default=1000,
                    help="LSTM save frequency, default: %(default)s")
parser.add_argument("--strip",action="store_false",
                    help="strip the model before saving")
parser.add_argument("-N","--ntrain",type=int,default=1000000,
                    help="# lines to train before stopping, default: %(default)s")
parser.add_argument("-t","--tests",default=None,
                    help="test cases for error estimation")
parser.add_argument('--unidirectional',action="store_true",
                    help="use only unidirectional LSTM")
parser.add_argument("--updates",action="store_true",
                    help="verbose LSTM updates")
parser.add_argument('--load',default=None,
                    help="start training with a previously trained model")
parser.add_argument('--start',default=-1,type=int)

# debugging
parser.add_argument("-X","--exec",default="None",dest="execute",
                    help="execute before anything else (usually used for imports)")
parser.add_argument("-v","--verbose",action="store_true")
parser.add_argument("-d","--display",type=int,default=0,
                    help="display output for every nth iteration, where n=DISPLAY, default: %(default)s")
parser.add_argument("-m","--movie",default=None)
parser.add_argument("-M","--moviesample",default=None)
parser.add_argument("-q","--quiet",action="store_true")
parser.add_argument("-Q","--nocheck",action="store_true")
parser.add_argument("-p","--pad",type=int,default=16)

parser.add_argument("files",nargs="*")
args = parser.parse_args()

inputs = ocrolib.glob_all(args.files)
if len(inputs)==0:
    parser.print_help()
    sys.exit(0)

print "# inputs",len(inputs)

# pre-execute any python commands

exec args.execute

# make sure movie mode is used correctly

if args.movie is not None:
    if args.display<2:
        print "you must set --display to some number greater than 1"
        sys.exit(0)

if args.moviesample is None:
    args.moviesample = inputs[0]

# make sure an output file has been set

if args.output is None:
    print "you must give an output file with %d in it, or a prefix"
    sys.exit(0)

if not "%" in args.output:
    if args.clstm:
        oname = args.output+"-%08d.h5"
    else:
        oname = args.output+"-%08d.pyrnn"
else:
    oname = args.output

# get a separate test set, if present

tests = None
if args.tests is not None:
    tests = ocrolib.glob_all(args.tests.split(":"))
print "# tests",(len(tests) if tests is not None else "None")

# load the line normalizer

if args.lineest=="center":
  lnorm = lineest.CenterNormalizer()
else:
  raise Exception(args.lineest+": unknown line normalizer")
lnorm.setHeight(args.height)

# The `codec` maps between strings and arrays of integers.

if args.codec!=[]:
    print "# building codec"
    codec = lstm.Codec()
    charset = set()
    print args.codec
    for fname in ocrolib.glob_all(args.codec):
        #fix anscii issue
        transcript = ocrolib.read_text(fname).encode('utf-8')
        l = list(lstm.normalize_nfkc(transcript))
        charset = charset.union(l)
    charset = sorted(list(charset))
    charset = [c for c in charset if c>" " and c!="~"]
else:
    print "# using default codec"
    charset = sorted(list(set(list(lstm.ascii_labels) + list(ocrolib.chars.default))))

charset = [""," ","~",]+[c for c in charset if c not in [" ","~"]]
print "# charset size",len(charset),
if len(charset)<200:
    print ("["+"".join(charset)+"]").encode('utf-8').strip()
else:
    s = ("".join(charset)).encode('utf-8').strip()
    print "["+s[:20],"...",s[-20:]+"]"
codec = lstm.Codec().init(charset)

# Load an existing network or construct a new one
# Somewhat convoluted logic for dealing with old style Python
# modules and new style C++ LSTM networks.

def save_lstm(fname,network):
    if args.clstm:
        network.lstm.save(fname)
    else:
        if args.strip:
            network.clear_log()
            for x in network.walk(): x.preSave()
        ocrolib.save_object(fname,network)
        if args.strip:
            for x in network.walk(): x.postLoad()

def load_lstm(fname):
    if args.clstm:
        network = lstm.SeqRecognizer(args.height,args.hiddensize,
            codec=codec,
            normalize=lstm.normalize_nfkc)
        import clstm
        mylstm = clstm.make_BIDILSTM()
        mylstm.init(network.No,args.hiddensize,network.Ni)
        mylstm.load(fname)
        network.lstm = clstm.CNetwork(mylstm)
        return network
    else:
        network = ocrolib.load_object(last_save)
        network.upgrade()
        for x in network.walk(): x.postLoad()
        return network

if args.load:
    print "# loading",args.load
    last_save = args.load
    network = load_lstm(args.load)
else:
    last_save = None
    network = lstm.SeqRecognizer(args.height,args.hiddensize,
        codec=codec,
        normalize=lstm.normalize_nfkc)
    if args.clstm:
        import clstm
        mylstm = clstm.make_BIDILSTM()
        mylstm.init(network.No,args.hiddensize,network.Ni)
        network.lstm = clstm.CNetwork(mylstm)

if getattr(network,"lnorm",None) is None:
    network.lnorm = lnorm

network.upgrade()
if network.last_trial%100==99: network.last_trial += 1
print "# last_trial",network.last_trial


# set up the learning rate

network.setLearningRate(args.lrate,0.9)
if args.updates: network.lstm.verbose = 1

# used for plotting

ion()
matplotlib.rc('xtick',labelsize=7)
matplotlib.rc('ytick',labelsize=7)
matplotlib.rcParams.update({"font.size":7})

def cleandisp(s):
    return re.sub('[$]',r'#',s)

def plot_network_info(network,transcript,pred,gta):
    subplot(511)
    imshow(line.T,cmap=cm.gray)
    title(cleandisp(transcript))
    subplot(512)
    gca().set_xticks([])
    imshow(network.outputs.T[1:],vmin=0,cmap=cm.hot)
    title(cleandisp(pred[:len(transcript)]))
    subplot(513)
    imshow(network.aligned.T[1:],vmin=0,cmap=cm.hot)
    title(cleandisp(gta[:len(transcript)]))
    subplot(514)
    plot(network.outputs[:,0],color='yellow',linewidth=3,alpha=0.5)
    plot(network.outputs[:,1],color='green',linewidth=3,alpha=0.5)
    plot(amax(network.outputs[:,2:],axis=1),color='blue',linewidth=3,alpha=0.5)
    plot(network.aligned[:,0],color='orange',linestyle='dashed',alpha=0.7)
    plot(network.aligned[:,1],color='green',linestyle='dashed',alpha=0.5)
    plot(amax(network.aligned[:,2:],axis=1),color='blue',linestyle='dashed',alpha=0.5)
    subplot(515)
    gca().set_yscale('log')
    r = 10000
    errs = network.errors(range=r,smooth=100)
    xs = arange(len(errs))+network.last_trial-len(errs)
    plot(xs,errs,color='black')
    plot(xs,network.errors(range=r),color='black',alpha=0.4)
    plot(xs,network.cerrors(range=r,smooth=100),color='red',linestyle='dashed')

start = args.start if args.start>=0 else network.last_trial

for trial in range(start,args.ntrain):
    network.last_trial = trial+1

    do_display = (args.display>0 and trial%args.display==0)
    do_update = 1

    if args.movie and do_display:
        fname = args.moviesample
        do_update = 0
    else:
        fname = pyrandom.sample(inputs,1)[0]

    base,_ = ocrolib.allsplitext(fname)
    try:
        line = ocrolib.read_image_gray(fname)
        transcript = ocrolib.read_text(base+".gt.txt")
    except IOError as e:
        print "ERROR",e
        continue

    if not args.nolineest:
        assert "dew.png" not in fname,"don't dewarp already dewarped lines"
        network.lnorm.measure(amax(line)-line)
        line = network.lnorm.normalize(line,cval=amax(line))
    else:
        assert "dew.png" in fname,"input must already be dewarped"

    if line.size<10 or amax(line)==amin(line):
        print "EMPTY-INPUT"
        continue
    line = line * 1.0/amax(line)
    line = amax(line)-line
    line = line.T
    if args.pad>0:
        w = line.shape[1]
        line = vstack([zeros((args.pad,w)),line,zeros((args.pad,w))])
    cs = array(codec.encode(transcript),'i')
    try:
        pcs = network.trainSequence(line,cs,update=do_update,key=fname)
    except FloatingPointError as e:
        print "# oops, got FloatingPointError",e
        traceback.print_exc()
        network = load_lstm(last_save)
        continue
    except lstm.RangeError as e:
        continue
    pred = "".join(codec.decode(pcs))
    acs = lstm.translate_back(network.aligned)
    gta = "".join(codec.decode(acs))
    if not args.quiet:
        print "%d %.2f %s"%(trial,network.error,line.shape),fname
        print "   TRU:",repr(transcript)
        print "   ALN:",repr(gta[:len(transcript)+5])
        print "   OUT:",repr(pred[:len(transcript)+5])

    pred = re.sub(' ','_',pred)
    gta = re.sub(' ','_',gta)

    if (trial+1)%args.savefreq==0:
        ofile = oname%(trial+1)+".gz"
        print "# saving",ofile
        save_lstm(ofile,network)
        last_save = ofile

    if do_display:
        figure("training",figsize=(1400//75,800//75),dpi=75)
        clf()
        gcf().canvas.set_window_title(args.output)
        plot_network_info(network,transcript,pred,gta)
        ginput(1,0.01)
        if args.movie is not None:
            draw()
            savefig("%s-%08d.png"%(args.movie,trial),bbox_inches=0)


```

**Comment by kba** [comment]
@wanghaisheng Please don't post the full contents of the scripts you changed. I did not **suggest** that you change the script, I only posted the diff between the [current master version of `ocropus-rtrain](https://github.com/kba/ocropy/blob/master/ocropus-rtrain) and the script you posted earlier.

It looks like in `/ocropy/ocrolib/lineest.py`, line 54, the mean of `NaN` is calculated which causes the "RuntimeWarning: Mean of empty slice" and subsequently there is a  division by zero.

**Comment by anupamaray** [comment]
@wanghaisheng could u solve this error.. If yes please let me know how you did that. 
I have same error 
`/usr/lib/python2.7/dist-packages/numpy/core/_methods.py:55: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
Traceback (most recent call last):
  File "./ocropus-rtrain", line 270, in <module>
    network.lnorm.measure(amax(line)-line)
  File "/home/mmlab/Downloads/ocropy-master/ocrolib/lineest.py", line 43, in measure
    self.mad = mean(deltas[line!=0])
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2716, in mean
    out=out, keepdims=keepdims)
  File "/usr/lib/python2.7/dist-packages/numpy/core/_methods.py", line 67, in _mean
    ret = ret.dtype.type(ret / rcount)
FloatingPointError: invalid value encountered in double_scalars
`

**Comment by Ekleog** [comment]
I'm having the same issue with `ocropus-20170811`, with training data generated with `ocropus-linegen`. As this is still open I guess it still happens, but if there's anything I can do to help about it… :)
